version: '3.7'

services:
  postgres:
    container_name: '${SERVICE_NAME}-postgres'
    image: postgres:14.0-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/data/postgres
      - ./seed:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - PGDATA=/data/postgres
